source "https://github.com/CocoaPods/Specs.git"
platform :ios, "8.0"
use_frameworks!

target "MVVM" do

pod 'FDFullscreenPopGesture', '~> 1.1'
pod 'Masonry', '~> 1.0.0'
pod 'SDCycleScrollView', '~> 1.64'
pod 'IQKeyboardManager', '~> 4.0.3'
pod 'MJRefresh', '~> 3.1.0'
pod 'AFNetworking', '~> 3.1.0'        

pod 'MBProgressHUD', '~> 0.9.2'
pod 'ReactiveCocoa', '~> 4.2.1'
pod 'MJExtension', '~> 3.0.13'

end 
